### ISSUE TITLE
Create a modern landig page for pxilpay.tech

### ISSUE THREAD

**Issue by cojocaru-david** [pixlpay/website#1]
## Tasks

- [x] Find a color theme and logo
- [ ] Design the layout of the landing page
- [ ] Choose color scheme and fonts
- [ ] Code the HTML structure
- [ ] Style the page with CSS (consider using Tailwind CSS)
- [ ] Add interactive elements (e.g., buttons, forms)
- [ ] Optimize for mobile responsiveness
- [ ] Test across different browsers
- [ ] Add SEO meta tags and descriptions
- [ ] Optimize page performance (e.g., image compression)
- [ ] Deploy to production

**Comment by cojocaru-david** [comment]
## The colour theme will be (yellow-500) #f59e0b and all logos will be here: 
https://drive.google.com/file/d/1e24keMgiA8c9fDkY7XNNP3zN2W2VfFaR/view?usp=sharing

**Comment by james-gates-0212** [comment]
We require a platform for communication and exchange of ideas.
Would it be possible to connect on Skype, Slack, or Discord?

**Comment by cojocaru-david** [comment]
Discord is a great platform for communication and collaboration.

Here is the discord server https://discord.gg/jz6kv5aYf7
Or my discord username: cojocarudavid.
